#! /bin/bash

MIN()
{
	echo $(($1>$2 ? $2 : $1))
}

ERREXIT()
{
	local code
	code="$1"

	[[ $? -ne 0 ]] && code="$?"
	[[ -z $code ]] && code=99

	shift 1
	[[ -n $1 ]] && echo -e >&2 "ERROR: $*"

	exit "$code"
}

XMD5() { md5sum "${1}" 2>/dev/null | cut -f1 -d' '; }

# Load the list of relay hosts if no arg is specified. File looks like this:
# DOMAIN=bhsocket.io
# HOSTS+=("bh1")
# HOSTS+=("bh2")
# HOSTS+=("bh3")
[[ ${#@} -eq 0 ]] && source "${BASEDIR}/.gsrn_hosts"
# Otherwise use hosts from command line arguments.
[[ -z $HOSTS ]] && HOSTS=("${@}")
[[ -z $HOSTS ]] && { echo -e "$(basename "${0}") [gsrn-hostname] ..."; exit 255; }
:
